# Generated by Django 3.2.6 on 2021-08-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_data.subject'),
        ),
    ]
