# Generated by Django 3.2.6 on 2021-08-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_alter_marks_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.TextField(default='Bot'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.TextField(default='Man'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
